### PR TITLE
Replace all references to the "docker-compose" command

### PR DESCRIPTION
**Pull request by yaronkoren**
Only "docker compose" (no hyphen) is now supported

### CODE REVIEW

**Review by jeffw16 — COMMENTED** [review]
Can we specify that "docker-compose" is still supported when passed into the CLI's `-o` parameter for backwards compatibility? Everything else looks good.

**Review by freephile — APPROVED** [review]
These changes all look good

**Review by jeffw16 — CHANGES_REQUESTED** [review]
I am so sorry, but I really can't approve this change until we re-establish `-o docker-compose` as a backwards compatible option. It should not be that hard to implement and it's not too much to ask for. Changing the naming and not adding the backwards compatibility seems like bad practice.

**Comment by jeffw16** [comment]
To be clear, I'm not saying we should be using `docker-compose up -d` when running the commands. I'm only saying we should accept `-o docker-compose`

**Comment by yaronkoren** [comment]
@jeffw16 - it sounds like you just want the one line "(Currently Docker's `compose` plugin is the only orchestrator supported by the CLI)" changed to something like "(Currently two orchestrators are supported by the CLI: `compose` and `docker-compose`, although the latter is deprecated)". Is that correct?

**Comment by jeffw16** [comment]
The latter part is correct. But there is only one orchestrator; it just got renamed. All I'm asking for is the CLI to support backwards compatibility and then we can merge this PR in.

**Comment by jeffw16** [comment]
But fine, I suppose this documentation change itself has no inaccuracies, so it could theoretically be merged right now.

**Comment by yaronkoren** [comment]
Wait, are you asking for a change to the CLI code itself? Because that seems like a separate issue from what's in the documentation - the documentation should reflect the current state of the code.

**Comment by yaronkoren** [comment]
Oh, I missed your last comment. :) Alright. Adding in backwards compatibility does sound useful.

**Pull request merged**
