### PR TITLE
Update documentation to reflect usage / requirements with Compose V2

### PR DESCRIPTION
**Pull request by freephile**
The commit breaks down the prerequisites into "Docker Desktop" for Windows/Mac and "Use the Docker repos" for Linux.

A sample script is added for preparing an Ubuntu Host.

### CODE REVIEW

**Comment by freephile** [comment]
This documentation update is supported by pull request in the CLI https://github.com/CanastaWiki/Canasta-CLI/pull/98

**Comment by yaronkoren** [comment]
That's fair. Please don't remove it! Just a rename would be good.

**Comment by freephile** [comment]
This can go ahead of the code changes although this documentation does introduce a change in the behavior of the CLI installer (no side-effects unless all pre-requisites are present) which is not the current behavior.

I'm not exactly familiar with the release process (but I hope to learn more about it). Ideally the documentation and the code changes should be merged at the same time into a matching versioned release.

**Comment by jeffw16** [comment]
I can take a look at this at SMWCon.

**Comment by yaronkoren** [comment]
Sorry to jump the gun, but this change looks like a clear improvement. Feel free to revert anything that's wrong with it.

**Pull request merged**
